const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENTS = "NEW-ATTACHMENTS";
// console.log("NEW_ATTACHMENTS :", NEW_ATTACHMENTS);
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
// console.log("NEW_MESSAGE_ALERT :", NEW_MESSAGE_ALERT);

export { ALERT, REFETCH_CHATS, NEW_ATTACHMENTS, NEW_MESSAGE_ALERT };
